# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 14:32
from __future__ import unicode_literals

import Stadium.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[(Stadium.models.WeekDayChoice('FRIDAY'), 'FRIDAY'), (Stadium.models.WeekDayChoice('MONDAY'), 'MONDAY'), (Stadium.models.WeekDayChoice('SATURDAY'), 'SATURDAY'), (Stadium.models.WeekDayChoice('SUNDAY'), 'SUNDAY'), (Stadium.models.WeekDayChoice('THURSDAY'), 'THURSDAY'), (Stadium.models.WeekDayChoice('TUESDAY'), 'TUESDAY'), (Stadium.models.WeekDayChoice('WEDNESDAY'), 'WEDNESDAY')], max_length=2)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('join_date', models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 32, 49, 408359, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_parts', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 32, 49, 410493, tzinfo=utc))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.Orders')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.Parts')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='parts',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.Stadium'),
        ),
        migrations.AddField(
            model_name='orders',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.Stadium'),
        ),
        migrations.AddField(
            model_name='availability',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stadium.Stadium'),
        ),
    ]
