# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 32, 53, 545800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 32, 53, 547906, tzinfo=utc)),
        ),
    ]
