# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Stadium', '0002_auto_20181014_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 46, 17, 472858, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 46, 17, 472828, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 46, 17, 470607, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 14, 46, 17, 472877, tzinfo=utc)),
        ),
    ]
